- name: Upgrade all packages
  yum:
    name: '*'
    state: latest

- name: Install httpd
  yum:
    name: httpd
    state: present

- name: Enable and start httpd service
  systemd:
    name: httpd
    state: started
    enabled: yes